---
# defaults file for wordpress
wordpress_packages:
  - httpd
  - mysql
  - python-pip
  - gcc
  - mysql-devel
  - php
  - php-mysqlnd
  - php-mbstring

wordpress_database_host: 'terraform-20230301220519871100000004.cjgnhlulqlqg.us-east-1.rds.amazonaws.com'
wordpress_database: 'wordpress'
wordpress_user: 'admin'
wordpress_password: 'adminroot'
wordpress_configuration: '/var/www/html/wp-config.php'